[build-system]
requires = ["setuptools>=80.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "modrinth4py"
description = "A Python API client for the Modrinth API"
version = "0.0.0" # set by uv during release
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
authors = [{ name = "rotgruengelb", email = "daniel+modrinth4py@rotgruengelb.net" }]
keywords = ["modrinth", "api", "client", "minecraft", "mods"]
dependencies = ["requests>=2.32.5"]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Development Status :: 4 - Beta",
]

[project.urls]
Homepage = "https://github.com/rotgruengelb/modrinth4py"
Documentation = "https://github.com/rotgruengelb/modrinth4py#readme"
Source = "https://github.com/rotgruengelb/modrinth4py"
Tracker = "https://github.com/rotgruengelb/modrinth4py/issues"

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests", "tests.*"]

[tool.pytest.ini_options]
testpaths = ["tests"]